package com.employeemanagement.backend.entity;

import java.util.Objects;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * Entity for request resource.
 */
@Entity
public class RequestResource {
    /**
     * Autogenerated primary key field.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    /**
     * Manager id.
     */
    @Column(nullable = false)
    private Long managerId;
    /**
     * Employee id.
     */
    @Column(nullable = false)
    private Long employeeId;
    /**
     * Comment for request resource.
     */
    @Column(nullable = false)
    private String comment;
    /**
     * Project Id.
     */
    @Column(nullable = false)
    private Long projectId;

    /**
     * Used to generate hashcode.
     */
    @Override
    public int hashCode() {
        return Objects.hash(comment, employeeId, id, managerId, projectId);
    }

    /**
     * Method used to compare two objects.
     */
    @Override
    public boolean equals(final Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        RequestResource other = (RequestResource) obj;
        return Objects.equals(comment, other.comment)
                && Objects.equals(employeeId, other.employeeId)
                && Objects.equals(id, other.id)
                && Objects.equals(managerId, other.managerId)
                && Objects.equals(projectId, other.projectId);
    }

    /**
     * Used to get values of obejct.
     */
    @Override
    public String toString() {
        return "RequestResource [id=" + id + ", managerId=" + managerId
                + ", employeeId=" + employeeId + ", comment=" + comment
                + ", projectId=" + projectId + "]";
    }

    /**
     * @return the id
     */
    public Long getId() {
        return id;
    }

    /**
     * @param resourceId the id to set
     */
    public void setId(final Long resourceId) {
        this.id = resourceId;
    }

    /**
     * @return the managerId
     */
    public Long getManagerId() {
        return managerId;
    }

    /**
     * @param resourceManagerId the managerId to set
     */
    public void setManagerId(final Long resourceManagerId) {
        this.managerId = resourceManagerId;
    }

    /**
     * @return the employeeId
     */
    public Long getEmployeeId() {
        return employeeId;
    }

    /**
     * @param requestEmployeeId the employeeId to set
     */
    public void setEmployeeId(final Long requestEmployeeId) {
        this.employeeId = requestEmployeeId;
    }

    /**
     * @return the comment
     */
    public String getComment() {
        return comment;
    }

    /**
     * @param resourceComment the comment to set
     */
    public void setComment(final String resourceComment) {
        this.comment = resourceComment;
    }

    /**
     * @return the projectId
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * @param long1 the projectId to set
     */
    public void setProjectId(final Long long1) {
        this.projectId = long1;
    }

}
